apiVersion: v1
kind: Service
metadata:
  name: user-validation-service
spec:
  ports:
  - port: 80
    targetPort: ms-port
    protocol: TCP
  selector:
    app: user-validation
  type: LoadBalancer  
