apiVersion: v1
kind: Pod
metadata:
  name: user-validation-pod
  labels:
    app: user-validation
spec:
  containers:
  - name: user-validation
    image: pengyue/ms-user-validation
    ports:
    - name: ms-port
      containerPort: 80
