apiVersion: v1
kind: ReplicationController
metadata:
  name: user-validation-rc
spec:
  replicas: 5
  selector:
    app: user-validation
  template:
    metadata:
      labels:
        app: user-validation
    spec:
      containers:
      - name: user-validation-container
        image: pengyue/ms-user-validation:v1
        ports:
        - name: ms-port
          containerPort: 80