homepage:
    prefix:   "/"
    resource: "@ApiBundle/Resources/config/routing/homepage.yml"
api_v1:
    prefix:   "/api/v1"
    type:     "rest"
    resource: "@ApiBundle/Resources/config/routing/api_v1.yml"
api_v2:
    prefix:   "/api/v2"
    type:     "rest"
    resource: "@ApiBundle/Resources/config/routing/api_v2.yml"
NelmioApiDocBundle:
    prefix:   "/api/doc"
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"